-- =============================================================================
-- Crystal Procurement & Asset Management — database schema
-- Target: PostgreSQL 15+
-- Reference: CG-PROC-BSOP-003 v2.0 and the canvas mockups (screens 1–15)
--
-- Conventions
--   * bigint identity primary keys; human-readable document numbers
--     (MR-Dhulagarh-Sep2026/0047) are separate UNIQUE columns generated by
--     next_document_no() at insert time.
--   * Money numeric(14,2); quantities numeric(14,3).
--   * Every workflow table carries status, created_*/updated_* audit columns.
--   * stock_ledger and audit_log are append-only (trigger-enforced).
--   * Stock is never written directly: stock_balances is maintained only by
--     post_stock_movement().
--   * Users come from Crystal Core SSO; app_users mirrors them for FKs.
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;

-- -----------------------------------------------------------------------------
-- 0. Enumerations (mirror the state machines in SOP section 5)
-- -----------------------------------------------------------------------------
CREATE TYPE record_status      AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE site_type          AS ENUM ('PLANT', 'DEPOT', 'PROJECT_SITE', 'WAREHOUSE');
CREATE TYPE role_code          AS ENUM ('CG_REQ', 'CG_SMGR', 'CG_BUY', 'CG_RCV', 'CG_QC', 'CG_WHL', 'CG_ACC', 'CG_ADM', 'CG_FHEAD', 'CG_DIR');
CREATE TYPE vendor_status      AS ENUM ('VENDOR_DRAFT', 'VENDOR_PENDING', 'VENDOR_APPROVED', 'VENDOR_BLOCKED', 'VENDOR_INACTIVE');
CREATE TYPE approval_state     AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE category_code      AS ENUM ('MAINTENANCE_CAPEX', 'OPERATIONS_CAPEX', 'PROJECT_SITE_CAPEX', 'SERVICE', 'CONSUMABLES', 'ASSETS');
CREATE TYPE procurement_type   AS ENUM ('MATERIAL', 'SERVICE');
CREATE TYPE urgency_code       AS ENUM ('ROUTINE', 'PLANNED', 'URGENT', 'EMERGENCY');

CREATE TYPE stock_bucket       AS ENUM ('AVAILABLE', 'RESERVED', 'IN_TRANSIT', 'DAMAGED_HOLD', 'UNDER_REPAIR', 'WRITTEN_OFF');
CREATE TYPE movement_type      AS ENUM ('OPENING', 'GRN_RECEIPT', 'ISSUE', 'TRANSFER_RESERVE', 'TRANSFER_OUT', 'TRANSFER_IN',
                                        'DAMAGE_QUARANTINE', 'REPAIR_START', 'REPAIR_COMPLETE', 'WRITE_OFF', 'RTV_REVERSAL',
                                        'ADJUSTMENT', 'REVERSAL');

CREATE TYPE mr_status          AS ENUM ('MR_DRAFT', 'MR_STOCK_CHECK', 'MR_STOCK_AVAILABLE', 'MR_STOCK_PARTIAL', 'MR_STOCK_UNAVAILABLE',
                                        'MR_TRANSFER_REQUESTED', 'MR_TRANSFER_APPROVED', 'MR_TRANSFER_REJECTED', 'MR_DECLARED',
                                        'MR_APPROVED', 'MR_REJECTED', 'MR_CONVERTED_TO_PR', 'MR_FULFILLED_INTERNAL', 'MR_CANCELLED');
CREATE TYPE transfer_status    AS ENUM ('TRF_REQUESTED', 'TRF_APPROVED', 'TRF_REJECTED', 'TRF_DISPATCHED', 'TRF_RECEIVED', 'TRF_CANCELLED');
CREATE TYPE pr_status          AS ENUM ('PR_DRAFT', 'PR_SUBMITTED', 'PR_APPROVED', 'PR_REJECTED', 'PO_POSTED', 'PR_CLOSED', 'PR_CANCELLED');
CREATE TYPE quotation_status   AS ENUM ('QUOTE_RECEIVED', 'QUOTE_AWARDED', 'QUOTE_LOST', 'QUOTE_EXPIRED', 'QUOTE_WITHDRAWN');
CREATE TYPE po_status          AS ENUM ('PO_DRAFT', 'PO_CREATED', 'PO_PARTIALLY_RECEIVED', 'PO_RECEIVED', 'PO_SHORT_CLOSED', 'PO_CLOSED', 'PO_CANCELLED');

CREATE TYPE gate_status        AS ENUM ('INWARD_RECEIVED', 'INWARD_REJECTED', 'QC_PENDING', 'QC_IN_PROGRESS', 'QC_COMPLETED');
CREATE TYPE qc_line_verdict    AS ENUM ('QC_ACCEPTED', 'QC_CONDITIONAL_HOLD', 'QC_ACCEPTED_CONCESSION', 'QC_REJECTED');
CREATE TYPE checklist_result   AS ENUM ('PASS', 'FAIL', 'NA');
CREATE TYPE hold_decision      AS ENUM ('CONCESSION', 'REJECT');
CREATE TYPE grn_status         AS ENUM ('GRN_DRAFT', 'GRN_APPROVED', 'GRN_REJECTED', 'GRN_FLAGGED', 'GRN_CLOSED');
CREATE TYPE shortfall_decision AS ENUM ('PENDING', 'AWAIT_BALANCE', 'SHORT_CLOSE');

CREATE TYPE damage_cause       AS ENUM ('HANDLING', 'STORAGE_FAILURE', 'POWER_REFRIGERATION_FAILURE', 'PEST_CONTAMINATION', 'INTERNAL_TRANSIT', 'EXPIRY', 'UNKNOWN');
CREATE TYPE damage_status      AS ENUM ('DMG_REPORTED', 'DMG_INSPECTED', 'DMG_DECISION_PENDING_APPROVAL', 'DMG_UNDER_REPAIR', 'DMG_RETURN_RAISED', 'DMG_WRITTEN_OFF', 'DMG_CLOSED');
CREATE TYPE damage_decision    AS ENUM ('INTERNAL_REPAIR', 'WARRANTY_CLAIM', 'WRITE_OFF');

CREATE TYPE rtv_source         AS ENUM ('QC_REJECTION', 'WAREHOUSE_DAMAGE', 'SHORTFALL');
CREATE TYPE rtv_basis          AS ENUM ('CREDIT', 'REPLACEMENT', 'FREE_REPLACEMENT', 'REPAIR_AND_RETURN');
CREATE TYPE rtv_status         AS ENUM ('RTV_DRAFT', 'RTV_APPROVED', 'RTV_DISPATCHED', 'RTV_ACKNOWLEDGED', 'RTV_CLOSED', 'RTV_CANCELLED');

CREATE TYPE dn_status          AS ENUM ('DEBIT_NOTE_PENDING', 'DEBIT_NOTE_ISSUED', 'CREDIT_NOTE_RECEIVED', 'DN_ADJUSTED', 'DN_RECONCILED', 'DN_CANCELLED');
CREATE TYPE invoice_status     AS ENUM ('INV_RECEIVED', 'INV_MATCHED', 'INV_PARTIALLY_HELD', 'INV_RELEASED', 'INV_PAID', 'INV_DISPUTED');
CREATE TYPE ledger_side        AS ENUM ('PORTAL', 'TALLY');
CREATE TYPE recon_match        AS ENUM ('MATCHED', 'AMOUNT_DIFFERS', 'ONLY_IN_PORTAL', 'ONLY_IN_TALLY', 'MATCHED_TO_DN', 'OPEN_ITEM');
CREATE TYPE recon_status       AS ENUM ('RECON_OPEN', 'RECON_DIFFERENCE', 'RECON_RECONCILED', 'RECON_CONFIRMED_BY_VENDOR');

-- -----------------------------------------------------------------------------
-- Shared helpers
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is append-only; post a reversing entry instead', TG_TABLE_NAME;
END $$;

-- =============================================================================
-- 1. IDENTITY, SITES AND MASTER DATA
-- =============================================================================

-- Mirror of Crystal Core identities (never a local login)
CREATE TABLE app_users (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  core_user_id    text        NOT NULL UNIQUE,          -- Crystal Core subject id
  email           citext      NOT NULL UNIQUE,
  full_name       text        NOT NULL,
  status          record_status NOT NULL DEFAULT 'ACTIVE',
  synced_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sites (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code                text        NOT NULL UNIQUE,      -- immutable once transacted (trigger below)
  name                text        NOT NULL,
  site_type           site_type   NOT NULL,
  address             text        NOT NULL,
  state_code          char(2)     NOT NULL,             -- GST state code, drives CGST/SGST vs IGST
  gstin               char(15)    NOT NULL,
  cold_chain_capable  boolean     NOT NULL DEFAULT false,
  tally_cost_centre   text,                             -- required before activation
  tally_branch        text,
  status              record_status NOT NULL DEFAULT 'INACTIVE',
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sites_gstin_format CHECK (gstin ~ '^[0-9]{2}[A-Z0-9]{10}[0-9A-Z]{3}$'),
  CONSTRAINT sites_gstin_state  CHECK (substr(gstin, 1, 2) = state_code),
  CONSTRAINT sites_active_needs_mapping CHECK (status <> 'ACTIVE' OR tally_cost_centre IS NOT NULL)
);

CREATE TABLE storage_locations (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  site_id     bigint NOT NULL REFERENCES sites(id),
  code        text   NOT NULL,                          -- e.g. RACK-C-04
  description text,
  is_cold     boolean NOT NULL DEFAULT false,
  status      record_status NOT NULL DEFAULT 'ACTIVE',
  UNIQUE (site_id, code)
);

CREATE TABLE user_site_roles (
  user_id   bigint    NOT NULL REFERENCES app_users(id),
  site_id   bigint    NOT NULL REFERENCES sites(id),
  role      role_code NOT NULL,
  granted_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, site_id, role)
);

CREATE TABLE budget_codes (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code         text          NOT NULL,
  financial_year text        NOT NULL,                  -- FY26-27
  site_id      bigint REFERENCES sites(id),             -- NULL = group-wide
  category     category_code,
  description  text,
  is_active    boolean NOT NULL DEFAULT true,
  UNIQUE (code, financial_year)
);

-- Value-banded approval matrix (PR, write-off, non-lowest award)
CREATE TABLE approval_bands (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type  text        NOT NULL CHECK (entity_type IN ('PR', 'WRITE_OFF', 'NON_LOWEST_AWARD', 'QUOTE_WAIVER')),
  min_value    numeric(14,2) NOT NULL,
  max_value    numeric(14,2),                           -- NULL = no upper limit
  label        text        NOT NULL,                    -- "₹1–10 lakh"
  is_active    boolean     NOT NULL DEFAULT true
);

CREATE TABLE approval_band_levels (
  band_id     bigint    NOT NULL REFERENCES approval_bands(id) ON DELETE CASCADE,
  level_no    smallint  NOT NULL,
  role        role_code NOT NULL,
  PRIMARY KEY (band_id, level_no)
);

-- Item catalogue
CREATE TABLE item_classes (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code              text    NOT NULL UNIQUE,
  name              text    NOT NULL,
  is_cold_chain     boolean NOT NULL DEFAULT false,
  temp_min_c        numeric(5,1),
  temp_max_c        numeric(5,1),
  requires_data_logger boolean NOT NULL DEFAULT false,
  CONSTRAINT item_classes_temp CHECK (NOT is_cold_chain OR (temp_min_c IS NOT NULL AND temp_max_c IS NOT NULL AND temp_min_c < temp_max_c))
);

CREATE TABLE items (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code             text    NOT NULL UNIQUE,              -- CC-EVP-220
  name             text    NOT NULL,
  item_class_id    bigint  NOT NULL REFERENCES item_classes(id),
  uom              text    NOT NULL,
  hsn_sac          text,
  default_gst_rate numeric(5,2) NOT NULL DEFAULT 18,
  is_serialised    boolean NOT NULL DEFAULT false,
  warranty_months  smallint,
  status           record_status NOT NULL DEFAULT 'ACTIVE',
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE item_site_settings (
  item_id        bigint NOT NULL REFERENCES items(id),
  site_id        bigint NOT NULL REFERENCES sites(id),
  reorder_level  numeric(14,3) NOT NULL DEFAULT 0,
  reorder_qty    numeric(14,3),
  PRIMARY KEY (item_id, site_id)
);

-- Vendor master
CREATE TABLE vendors (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vendor_code      text   NOT NULL UNIQUE,              -- V-0231
  legal_name       text   NOT NULL,
  vendor_type      text   NOT NULL DEFAULT 'COMPANY',
  pan              char(10) NOT NULL,
  gstin            char(15),
  state_code       char(2)  NOT NULL,
  address          text     NOT NULL,
  contact_name     text,
  contact_email    citext,
  contact_phone    text,
  msme_number      text,
  tally_ledger_ref text,                                -- required at approval
  status           vendor_status NOT NULL DEFAULT 'VENDOR_DRAFT',
  blocked_reason   text,
  blocked_from     date,
  created_by       bigint REFERENCES app_users(id),
  approved_by      bigint REFERENCES app_users(id),
  approved_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vendors_pan_format   CHECK (pan ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'),
  CONSTRAINT vendors_gstin_format CHECK (gstin IS NULL OR gstin ~ '^[0-9]{2}[A-Z0-9]{10}[0-9A-Z]{3}$'),
  CONSTRAINT vendors_gstin_pan    CHECK (gstin IS NULL OR substr(gstin, 3, 10) = pan),
  CONSTRAINT vendors_approved_needs_ledger CHECK (status <> 'VENDOR_APPROVED' OR tally_ledger_ref IS NOT NULL),
  CONSTRAINT vendors_blocked_reason CHECK (status <> 'VENDOR_BLOCKED' OR blocked_reason IS NOT NULL)
);
-- De-duplication survives case and whitespace (US-006)
CREATE UNIQUE INDEX vendors_pan_uq   ON vendors (upper(btrim(pan)));
CREATE UNIQUE INDEX vendors_gstin_uq ON vendors (upper(btrim(gstin))) WHERE gstin IS NOT NULL;

-- Bank details under maker-checker: only one APPROVED row is live
CREATE TABLE vendor_bank_accounts (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vendor_id         bigint NOT NULL REFERENCES vendors(id),
  account_number_enc bytea NOT NULL,                    -- encrypted at application layer
  account_last4     char(4) NOT NULL,
  ifsc              char(11) NOT NULL CHECK (ifsc ~ '^[A-Z]{4}0[A-Z0-9]{6}$'),
  beneficiary_name  text   NOT NULL,
  state             approval_state NOT NULL DEFAULT 'PENDING',
  proposed_by       bigint NOT NULL REFERENCES app_users(id),
  approved_by       bigint REFERENCES app_users(id),
  approved_at       timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vba_maker_checker CHECK (approved_by IS NULL OR approved_by <> proposed_by)
);
CREATE UNIQUE INDEX vba_one_live ON vendor_bank_accounts (vendor_id) WHERE state = 'APPROVED';

CREATE TABLE vendor_categories (
  vendor_id     bigint NOT NULL REFERENCES vendors(id),
  item_class_id bigint NOT NULL REFERENCES item_classes(id),
  PRIMARY KEY (vendor_id, item_class_id)
);

CREATE TABLE vendor_sites (
  vendor_id bigint NOT NULL REFERENCES vendors(id),
  site_id   bigint NOT NULL REFERENCES sites(id),
  PRIMARY KEY (vendor_id, site_id)
);

-- Atomic document numbering (fixes the v1.0 read-increment-write race)
CREATE TABLE id_counters (
  entity      text   NOT NULL,                          -- MR, PR, PO, GI, QC, GRN, DMG, SHT, RTV, RGP, DN, TRF, SL, ISS
  site_code   text   NOT NULL,
  period      text   NOT NULL,                          -- Sep2026
  last_serial integer NOT NULL DEFAULT 0,
  PRIMARY KEY (entity, site_code, period)
);

CREATE OR REPLACE FUNCTION next_document_no(p_entity text, p_site_code text, p_at timestamptz DEFAULT now())
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
  v_period text := to_char(p_at, 'FMMonYYYY');
  v_serial integer;
BEGIN
  INSERT INTO id_counters (entity, site_code, period, last_serial)
  VALUES (p_entity, p_site_code, v_period, 1)
  ON CONFLICT (entity, site_code, period)
  DO UPDATE SET last_serial = id_counters.last_serial + 1
  RETURNING last_serial INTO v_serial;
  RETURN p_entity || '-' || p_site_code || '-' || v_period || '/' || lpad(v_serial::text, 4, '0');
END $$;

-- =============================================================================
-- 2. INVENTORY — ledger, balances, serialised assets, transfers, issues
-- =============================================================================

-- Append-only movement log. A bucket move writes one row with from/to buckets.
CREATE TABLE stock_ledger (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entry_no            text   NOT NULL UNIQUE,           -- SL-DHU-104881
  site_id             bigint NOT NULL REFERENCES sites(id),
  item_id             bigint NOT NULL REFERENCES items(id),
  location_id         bigint REFERENCES storage_locations(id),
  asset_unit_id       bigint,                           -- FK added after asset_units
  movement            movement_type NOT NULL,
  from_bucket         stock_bucket,                     -- NULL = coming from outside the site
  to_bucket           stock_bucket,                     -- NULL = leaving the site
  qty                 numeric(14,3) NOT NULL CHECK (qty > 0),
  unit_value          numeric(14,2),                    -- rate from the source GRN
  source_type         text   NOT NULL,                  -- GRN_LINE, TRANSFER_LINE, DAMAGE_REPORT, RTV_LINE, ISSUE_LINE, OPENING
  source_id           bigint NOT NULL,
  reverses_entry_id   bigint REFERENCES stock_ledger(id),
  idempotency_key     text   NOT NULL UNIQUE,           -- e.g. 'GRN_LINE:8812' — replay-safe
  posted_by           bigint NOT NULL REFERENCES app_users(id),
  posted_at           timestamptz NOT NULL DEFAULT now(),
  remarks             text,
  CONSTRAINT sl_has_direction CHECK (from_bucket IS NOT NULL OR to_bucket IS NOT NULL),
  CONSTRAINT sl_bucket_change CHECK (from_bucket IS DISTINCT FROM to_bucket)
);
CREATE INDEX stock_ledger_item_site_idx ON stock_ledger (site_id, item_id, posted_at);
CREATE INDEX stock_ledger_source_idx    ON stock_ledger (source_type, source_id);
CREATE TRIGGER stock_ledger_append_only BEFORE UPDATE OR DELETE ON stock_ledger
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

-- Projection of the ledger. Written only by post_stock_movement().
CREATE TABLE stock_balances (
  site_id     bigint NOT NULL REFERENCES sites(id),
  item_id     bigint NOT NULL REFERENCES items(id),
  bucket      stock_bucket NOT NULL,
  qty         numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty >= 0),   -- stock can never go negative
  last_entry_id bigint REFERENCES stock_ledger(id),
  PRIMARY KEY (site_id, item_id, bucket)
);

CREATE OR REPLACE FUNCTION post_stock_movement(
  p_site_id bigint, p_item_id bigint, p_movement movement_type,
  p_from stock_bucket, p_to stock_bucket, p_qty numeric,
  p_source_type text, p_source_id bigint, p_user bigint,
  p_unit_value numeric DEFAULT NULL, p_location bigint DEFAULT NULL,
  p_asset_unit bigint DEFAULT NULL, p_reverses bigint DEFAULT NULL, p_remarks text DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
  v_key   text := p_source_type || ':' || p_source_id || ':' || p_movement;
  v_id    bigint;
  v_site  text;
BEGIN
  SELECT id INTO v_id FROM stock_ledger WHERE idempotency_key = v_key;
  IF FOUND THEN RETURN v_id; END IF;                    -- replay: already posted

  SELECT code INTO v_site FROM sites WHERE id = p_site_id;

  INSERT INTO stock_ledger (entry_no, site_id, item_id, location_id, asset_unit_id, movement, from_bucket, to_bucket,
                            qty, unit_value, source_type, source_id, reverses_entry_id, idempotency_key, posted_by, remarks)
  VALUES (next_document_no('SL', v_site), p_site_id, p_item_id, p_location, p_asset_unit, p_movement, p_from, p_to,
          p_qty, p_unit_value, p_source_type, p_source_id, p_reverses, v_key, p_user, p_remarks)
  RETURNING id INTO v_id;

  IF p_from IS NOT NULL THEN
    UPDATE stock_balances SET qty = qty - p_qty, last_entry_id = v_id
     WHERE site_id = p_site_id AND item_id = p_item_id AND bucket = p_from;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'No % stock for item % at site %', p_from, p_item_id, p_site_id;
    END IF;                                             -- CHECK (qty >= 0) blocks overdraw
  END IF;

  IF p_to IS NOT NULL THEN
    INSERT INTO stock_balances (site_id, item_id, bucket, qty, last_entry_id)
    VALUES (p_site_id, p_item_id, p_to, p_qty, v_id)
    ON CONFLICT (site_id, item_id, bucket)
    DO UPDATE SET qty = stock_balances.qty + EXCLUDED.qty, last_entry_id = EXCLUDED.last_entry_id;
  END IF;

  RETURN v_id;
END $$;

-- Serialised units (asset tags)
CREATE TABLE asset_units (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  asset_tag         text   NOT NULL UNIQUE,             -- DL-DHU-0419
  item_id           bigint NOT NULL REFERENCES items(id),
  serial_no         text,
  site_id           bigint NOT NULL REFERENCES sites(id),
  location_id       bigint REFERENCES storage_locations(id),
  bucket            stock_bucket NOT NULL DEFAULT 'AVAILABLE',
  source_grn_line_id bigint,                            -- FK added after grn_lines
  warranty_until    date,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE stock_ledger ADD CONSTRAINT stock_ledger_asset_fk FOREIGN KEY (asset_unit_id) REFERENCES asset_units(id);

CREATE TABLE stock_issues (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  issue_no    text   NOT NULL UNIQUE,                   -- ISS-Dhulagarh-Sep2026/0031
  site_id     bigint NOT NULL REFERENCES sites(id),
  issued_to   text   NOT NULL,                          -- department / work order
  issued_by   bigint NOT NULL REFERENCES app_users(id),
  issued_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE stock_issue_lines (
  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  issue_id  bigint NOT NULL REFERENCES stock_issues(id),
  item_id   bigint NOT NULL REFERENCES items(id),
  qty       numeric(14,3) NOT NULL CHECK (qty > 0)
);

-- =============================================================================
-- 3. MATERIAL REQUEST, STOCK CHECK AND TRANSFERS  (Module 1)
-- =============================================================================
CREATE TABLE material_requests (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  mr_no             text   NOT NULL UNIQUE,
  site_id           bigint NOT NULL REFERENCES sites(id),
  category          category_code NOT NULL,
  required_by       date   NOT NULL,
  urgency           urgency_code NOT NULL,
  status            mr_status NOT NULL DEFAULT 'MR_DRAFT',
  requester_id      bigint NOT NULL REFERENCES app_users(id),
  stock_checked_at  timestamptz,                        -- re-run if older than 72 h before PR
  approved_by       bigint REFERENCES app_users(id),
  approved_at       timestamptz,
  rejection_reason  text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mr_self_approval CHECK (approved_by IS NULL OR approved_by <> requester_id),
  CONSTRAINT mr_reject_reason CHECK (status <> 'MR_REJECTED' OR rejection_reason IS NOT NULL)
);
CREATE INDEX material_requests_site_status_idx ON material_requests (site_id, status);

CREATE TABLE mr_lines (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  mr_id            bigint NOT NULL REFERENCES material_requests(id) ON DELETE CASCADE,
  line_no          smallint NOT NULL,
  item_id          bigint NOT NULL REFERENCES items(id),
  qty_requested    numeric(14,3) NOT NULL CHECK (qty_requested > 0),
  qty_transfer     numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty_transfer >= 0),
  qty_purchase     numeric(14,3) GENERATED ALWAYS AS (qty_requested - qty_transfer) STORED,
  stock_check      jsonb,                               -- [{site_id, surplus_qty}] snapshot
  UNIQUE (mr_id, line_no),
  CONSTRAINT mr_lines_transfer_le CHECK (qty_transfer <= qty_requested)
);

CREATE TABLE mr_declarations (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  mr_id               bigint NOT NULL REFERENCES material_requests(id),
  version             smallint NOT NULL DEFAULT 1,
  business_impact     text   NOT NULL CHECK (char_length(business_impact) BETWEEN 40 AND 500),
  budget_code_id      bigint NOT NULL REFERENCES budget_codes(id),
  estimated_value     numeric(14,2) NOT NULL CHECK (estimated_value > 0),
  declaration_text_version text NOT NULL,
  accepted_by         bigint NOT NULL REFERENCES app_users(id),
  accepted_at         timestamptz NOT NULL DEFAULT now(),
  accepted_ip         inet,
  locked              boolean NOT NULL DEFAULT false,   -- true once a PR exists
  UNIQUE (mr_id, version)
);

CREATE TABLE mr_allocations (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  declaration_id  bigint NOT NULL REFERENCES mr_declarations(id) ON DELETE CASCADE,
  site_id         bigint NOT NULL REFERENCES sites(id),
  cost_head       text   NOT NULL,                      -- "Freezer block"
  pct             numeric(5,2) NOT NULL CHECK (pct > 0 AND pct <= 100)
);
-- Sum = 100% is enforced by trigger (a CHECK cannot span rows)
CREATE OR REPLACE FUNCTION check_allocation_total() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_total numeric;
BEGIN
  SELECT coalesce(sum(pct), 0) INTO v_total FROM mr_allocations
   WHERE declaration_id = coalesce(NEW.declaration_id, OLD.declaration_id);
  IF v_total <> 100 THEN
    RAISE EXCEPTION 'Site allocation must total 100%% (currently %)', v_total;
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER mr_allocations_total AFTER INSERT OR UPDATE OR DELETE ON mr_allocations
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_allocation_total();

CREATE TABLE stock_transfers (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  transfer_no     text   NOT NULL UNIQUE,               -- TRF-Pune-Sep2026/0007
  mr_id           bigint REFERENCES material_requests(id),
  from_site_id    bigint NOT NULL REFERENCES sites(id),
  to_site_id      bigint NOT NULL REFERENCES sites(id),
  status          transfer_status NOT NULL DEFAULT 'TRF_REQUESTED',
  requested_by    bigint NOT NULL REFERENCES app_users(id),
  decided_by      bigint REFERENCES app_users(id),    -- holding site's Warehouse Lead
  decided_at      timestamptz,
  rejection_reason text,
  dispatched_at   timestamptz,
  received_by     bigint REFERENCES app_users(id),
  received_at     timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT trf_sites_differ CHECK (from_site_id <> to_site_id),
  CONSTRAINT trf_reject_reason CHECK (status <> 'TRF_REJECTED' OR rejection_reason IS NOT NULL)
);

CREATE TABLE stock_transfer_lines (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  transfer_id  bigint NOT NULL REFERENCES stock_transfers(id) ON DELETE CASCADE,
  mr_line_id   bigint REFERENCES mr_lines(id),
  item_id      bigint NOT NULL REFERENCES items(id),
  qty          numeric(14,3) NOT NULL CHECK (qty > 0),
  qty_received numeric(14,3) CHECK (qty_received IS NULL OR qty_received >= 0)
);

-- =============================================================================
-- 4. PURCHASE REQUEST  (Module 2)
-- =============================================================================
CREATE TABLE purchase_requests (
  id                   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pr_no                text   NOT NULL UNIQUE,
  mr_id                bigint NOT NULL REFERENCES material_requests(id),   -- a PR cannot exist without an MR
  site_id              bigint NOT NULL REFERENCES sites(id),
  category             category_code NOT NULL,
  budget_code_id       bigint NOT NULL REFERENCES budget_codes(id),
  procurement_type     procurement_type NOT NULL,
  purpose              text   NOT NULL,
  suggested_vendor_id  bigint REFERENCES vendors(id),                      -- optional
  urgency              urgency_code NOT NULL,
  -- payment terms (percentages must total 100 unless a free-text override is used)
  pay_advance_pct          numeric(5,2) NOT NULL DEFAULT 0,
  pay_before_delivery_pct  numeric(5,2) NOT NULL DEFAULT 0,
  pay_running_pct          numeric(5,2) NOT NULL DEFAULT 0,
  pay_post_delivery_pct    numeric(5,2) NOT NULL DEFAULT 0,
  pay_post_completion_pct  numeric(5,2) NOT NULL DEFAULT 0,
  pay_retention_pct        numeric(5,2) NOT NULL DEFAULT 0,
  payment_terms_override   text,
  delivery_location_id     bigint REFERENCES storage_locations(id),
  expected_delivery        date   NOT NULL,
  delivery_chargeable      boolean NOT NULL DEFAULT false,
  delivery_charge_amount   numeric(14,2),
  delivery_charge_gst_rate numeric(5,2),
  approval_band_id         bigint REFERENCES approval_bands(id),
  status                   pr_status NOT NULL DEFAULT 'PR_DRAFT',
  requester_id             bigint NOT NULL REFERENCES app_users(id),
  locked_at                timestamptz,                -- set on approval; edits blocked after
  cancelled_reason         text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pr_payment_terms_total CHECK (
    payment_terms_override IS NOT NULL OR
    pay_advance_pct + pay_before_delivery_pct + pay_running_pct + pay_post_delivery_pct + pay_post_completion_pct + pay_retention_pct = 100),
  CONSTRAINT pr_delivery_charge CHECK (NOT delivery_chargeable OR (delivery_charge_amount IS NOT NULL AND delivery_charge_gst_rate IS NOT NULL)),
  CONSTRAINT pr_cancel_reason CHECK (status <> 'PR_CANCELLED' OR cancelled_reason IS NOT NULL)
);
CREATE INDEX purchase_requests_site_status_idx ON purchase_requests (site_id, status);

CREATE TABLE pr_lines (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pr_id       bigint NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
  line_no     smallint NOT NULL,
  mr_line_id  bigint NOT NULL REFERENCES mr_lines(id),
  item_id     bigint NOT NULL REFERENCES items(id),
  qty         numeric(14,3) NOT NULL CHECK (qty > 0),  -- locked to mr_lines.qty_purchase by trigger
  est_rate    numeric(14,2) NOT NULL CHECK (est_rate >= 0),
  gst_rate    numeric(5,2)  NOT NULL,
  UNIQUE (pr_id, line_no)
);

-- PR quantity must equal the MR purchase balance (US-104)
CREATE OR REPLACE FUNCTION check_pr_line_qty() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_bal numeric;
BEGIN
  SELECT qty_purchase INTO v_bal FROM mr_lines WHERE id = NEW.mr_line_id;
  IF NEW.qty <> v_bal THEN
    RAISE EXCEPTION 'PR quantity % must equal MR purchase balance %', NEW.qty, v_bal;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER pr_lines_qty_lock BEFORE INSERT OR UPDATE ON pr_lines
  FOR EACH ROW EXECUTE FUNCTION check_pr_line_qty();

-- Edit lock once the PR leaves PR_SUBMITTED (US-212)
CREATE OR REPLACE FUNCTION pr_edit_lock() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.locked_at IS NOT NULL AND (
       NEW.purpose, NEW.procurement_type, NEW.expected_delivery, NEW.delivery_chargeable,
       NEW.delivery_charge_amount, NEW.pay_advance_pct, NEW.pay_post_delivery_pct, NEW.pay_retention_pct)
     IS DISTINCT FROM (
       OLD.purpose, OLD.procurement_type, OLD.expected_delivery, OLD.delivery_chargeable,
       OLD.delivery_charge_amount, OLD.pay_advance_pct, OLD.pay_post_delivery_pct, OLD.pay_retention_pct) THEN
    RAISE EXCEPTION 'PR % is locked after approval', OLD.pr_no;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER purchase_requests_lock BEFORE UPDATE ON purchase_requests
  FOR EACH ROW EXECUTE FUNCTION pr_edit_lock();

-- Totals are always computed, never stored (v1.0 rule carried forward)
CREATE VIEW v_pr_totals AS
SELECT pr.id AS pr_id,
       sum(l.qty * l.est_rate)                                   AS taxable,
       sum(round(l.qty * l.est_rate * l.gst_rate / 100, 2))      AS gst,
       sum(round(l.qty * l.est_rate * (1 + l.gst_rate / 100), 2))
         + CASE WHEN pr.delivery_chargeable
                THEN round(pr.delivery_charge_amount * (1 + pr.delivery_charge_gst_rate / 100), 2) ELSE 0 END AS total_incl_gst
  FROM purchase_requests pr
  JOIN pr_lines l ON l.pr_id = pr.id
 GROUP BY pr.id;

-- Generic approval trail for MR, PR, non-lowest award, write-off, RTV, GRN, vendor, bank change
CREATE TABLE approvals (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type   text      NOT NULL,
  entity_id     bigint    NOT NULL,
  level_no      smallint  NOT NULL DEFAULT 1,
  required_role role_code NOT NULL,
  approver_id   bigint REFERENCES app_users(id),
  state         approval_state NOT NULL DEFAULT 'PENDING',
  remarks       text,
  decided_at    timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entity_type, entity_id, level_no)
);
CREATE INDEX approvals_pending_idx ON approvals (required_role, state) WHERE state = 'PENDING';

-- =============================================================================
-- 5. QUOTATIONS, COMPARISON AND AWARD
-- =============================================================================
CREATE TABLE quotations (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pr_id             bigint NOT NULL REFERENCES purchase_requests(id),
  vendor_id         bigint NOT NULL REFERENCES vendors(id),
  vendor_quote_ref  text   NOT NULL,
  quote_date        date   NOT NULL,
  valid_until       date   NOT NULL,
  freight_amount    numeric(14,2) NOT NULL DEFAULT 0,
  payment_terms     text,
  warranty_months   smallint,
  status            quotation_status NOT NULL DEFAULT 'QUOTE_RECEIVED',
  entered_by        bigint NOT NULL REFERENCES app_users(id),
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (pr_id, vendor_id),
  CONSTRAINT quotations_validity CHECK (valid_until >= quote_date)
);

CREATE TABLE quotation_lines (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  quotation_id    bigint NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  pr_line_id      bigint NOT NULL REFERENCES pr_lines(id),
  unit_rate       numeric(14,2) NOT NULL CHECK (unit_rate >= 0),
  gst_rate        numeric(5,2)  NOT NULL,
  lead_time_days  smallint,
  make            text,
  UNIQUE (quotation_id, pr_line_id)
);

-- Landed-cost comparison statement (US-2Q3)
CREATE VIEW v_quotation_landed_cost AS
SELECT q.id AS quotation_id, q.pr_id, q.vendor_id,
       sum(pl.qty * ql.unit_rate)                                          AS taxable,
       sum(round(pl.qty * ql.unit_rate * ql.gst_rate / 100, 2))            AS gst,
       q.freight_amount,
       sum(round(pl.qty * ql.unit_rate * (1 + ql.gst_rate / 100), 2)) + q.freight_amount AS landed_cost,
       rank() OVER (PARTITION BY q.pr_id
                    ORDER BY sum(round(pl.qty * ql.unit_rate * (1 + ql.gst_rate / 100), 2)) + q.freight_amount) AS rank_no
  FROM quotations q
  JOIN quotation_lines ql ON ql.quotation_id = q.id
  JOIN pr_lines pl        ON pl.id = ql.pr_line_id
 WHERE q.status IN ('QUOTE_RECEIVED', 'QUOTE_AWARDED', 'QUOTE_LOST')
 GROUP BY q.id;

CREATE TABLE quote_awards (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pr_id            bigint NOT NULL UNIQUE REFERENCES purchase_requests(id),
  quotation_id     bigint NOT NULL REFERENCES quotations(id),
  quotes_received  smallint NOT NULL,
  min_required     smallint NOT NULL DEFAULT 3,
  waiver_reason    text,                                -- below minimum quotes
  is_lowest        boolean NOT NULL,
  variance_to_l1   numeric(14,2) NOT NULL DEFAULT 0,
  reason_code      text,                                -- non-lowest award
  justification    text,
  awarded_by       bigint NOT NULL REFERENCES app_users(id),
  awarded_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT awards_waiver   CHECK (quotes_received >= min_required OR waiver_reason IS NOT NULL),
  CONSTRAINT awards_nonlow   CHECK (is_lowest OR (reason_code IS NOT NULL AND justification IS NOT NULL))
);

-- =============================================================================
-- 6. PURCHASE ORDER
-- =============================================================================
CREATE TABLE purchase_orders (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  po_no              text   NOT NULL UNIQUE,
  pr_id              bigint NOT NULL UNIQUE REFERENCES purchase_requests(id),   -- one PO per PR, enforced
  award_id           bigint REFERENCES quote_awards(id),
  vendor_id          bigint NOT NULL REFERENCES vendors(id),
  site_id            bigint NOT NULL REFERENCES sites(id),
  tally_po_ref       text   UNIQUE,                     -- required before issue
  po_date            date   NOT NULL DEFAULT current_date,
  expected_delivery  date   NOT NULL,
  freight_terms      text,
  installation_terms text,
  freight_amount     numeric(14,2) NOT NULL DEFAULT 0,
  status             po_status NOT NULL DEFAULT 'PO_DRAFT',
  buyer_id           bigint NOT NULL REFERENCES app_users(id),
  issued_at          timestamptz,
  short_close_reason text,
  cancelled_reason   text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT po_issue_needs_tally CHECK (status = 'PO_DRAFT' OR tally_po_ref IS NOT NULL),
  CONSTRAINT po_short_reason CHECK (status <> 'PO_SHORT_CLOSED' OR short_close_reason IS NOT NULL)
);
CREATE INDEX purchase_orders_vendor_idx ON purchase_orders (vendor_id, status);

CREATE TABLE po_lines (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  po_id         bigint NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  line_no       smallint NOT NULL,
  pr_line_id    bigint NOT NULL REFERENCES pr_lines(id),
  item_id       bigint NOT NULL REFERENCES items(id),
  qty_ordered   numeric(14,3) NOT NULL CHECK (qty_ordered > 0),
  rate          numeric(14,2) NOT NULL CHECK (rate >= 0),
  gst_rate      numeric(5,2)  NOT NULL,
  rate_deviation_remark text,                           -- required if rate differs from award
  UNIQUE (po_id, line_no)
);

-- Only an approved, unblocked vendor may appear on a PO (US-208)
CREATE OR REPLACE FUNCTION check_po_vendor() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_status vendor_status;
BEGIN
  SELECT status INTO v_status FROM vendors WHERE id = NEW.vendor_id;
  IF v_status <> 'VENDOR_APPROVED' THEN
    RAISE EXCEPTION 'Vendor % is % — only approved vendors can be ordered from', NEW.vendor_id, v_status;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER purchase_orders_vendor_check BEFORE INSERT OR UPDATE OF vendor_id ON purchase_orders
  FOR EACH ROW EXECUTE FUNCTION check_po_vendor();

-- =============================================================================
-- 7. RECEIVING — gate inward, QA/QC, GRN, shortfall  (Module 3)
-- =============================================================================
CREATE TABLE gate_inwards (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  gi_no               text   NOT NULL UNIQUE,
  po_id               bigint NOT NULL REFERENCES purchase_orders(id),
  site_id             bigint NOT NULL REFERENCES sites(id),
  vehicle_no          text   NOT NULL,
  driver_name         text,
  transporter         text,
  lr_no               text,
  seal_no             text,
  challan_no          text   NOT NULL,
  challan_date        date   NOT NULL,
  arrived_at          timestamptz NOT NULL DEFAULT now(),   -- server time, preserved through offline sync
  captured_offline    boolean NOT NULL DEFAULT false,
  reefer_set_point_c  numeric(5,1),
  reefer_actual_c     numeric(5,1),
  temp_in_tolerance   boolean,                              -- evaluated against item class bands
  is_replacement      boolean NOT NULL DEFAULT false,
  replacement_rtv_id  bigint,                               -- FK added after purchase_returns
  status              gate_status NOT NULL DEFAULT 'INWARD_RECEIVED',
  rejection_reason    text,
  received_by         bigint NOT NULL REFERENCES app_users(id),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gi_vehicle_format CHECK (vehicle_no ~ '^[A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{1,4}$'),
  CONSTRAINT gi_reject_reason  CHECK (status <> 'INWARD_REJECTED' OR rejection_reason IS NOT NULL),
  CONSTRAINT gi_replacement    CHECK (NOT is_replacement OR replacement_rtv_id IS NOT NULL)
);
CREATE UNIQUE INDEX gate_inwards_challan_uq ON gate_inwards (po_id, challan_no) WHERE status <> 'INWARD_REJECTED';

CREATE TABLE gate_inward_lines (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  gate_inward_id   bigint NOT NULL REFERENCES gate_inwards(id) ON DELETE CASCADE,
  po_line_id       bigint NOT NULL REFERENCES po_lines(id),
  qty_per_challan  numeric(14,3) NOT NULL CHECK (qty_per_challan >= 0),
  qty_counted      numeric(14,3) NOT NULL CHECK (qty_counted >= 0),   -- excess recorded, never auto-accepted
  qty_short        numeric(14,3) GENERATED ALWAYS AS (greatest(qty_per_challan - qty_counted, 0)) STORED,
  UNIQUE (gate_inward_id, po_line_id)
);

-- Versioned checklists per item class
CREATE TABLE qc_checklists (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_class_id  bigint NOT NULL REFERENCES item_classes(id),
  version        text   NOT NULL,                       -- HDPE-PAL v3
  is_current     boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (item_class_id, version)
);
CREATE UNIQUE INDEX qc_checklists_current ON qc_checklists (item_class_id) WHERE is_current;

CREATE TABLE qc_checklist_points (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  checklist_id  bigint NOT NULL REFERENCES qc_checklists(id) ON DELETE CASCADE,
  point_no      smallint NOT NULL,
  description   text   NOT NULL,
  UNIQUE (checklist_id, point_no)
);

CREATE TABLE qc_inspections (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  qc_no           text   NOT NULL UNIQUE,
  gate_inward_id  bigint NOT NULL UNIQUE REFERENCES gate_inwards(id),
  inspector_id    bigint NOT NULL REFERENCES app_users(id),
  started_at      timestamptz NOT NULL DEFAULT now(),
  completed_at    timestamptz,
  is_reinspection_of bigint REFERENCES qc_inspections(id),
  sla_due_at      timestamptz NOT NULL,                 -- +4 h cold-chain, +48 h ambient
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE qc_lines (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  qc_id               bigint NOT NULL REFERENCES qc_inspections(id) ON DELETE CASCADE,
  gate_inward_line_id bigint NOT NULL UNIQUE REFERENCES gate_inward_lines(id),
  checklist_id        bigint NOT NULL REFERENCES qc_checklists(id),   -- version stamp
  qty_delivered       numeric(14,3) NOT NULL,
  qty_accepted        numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty_accepted >= 0),
  qty_hold            numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty_hold >= 0),
  qty_rejected        numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty_rejected >= 0),
  reason_code         text,
  remarks             text,
  CONSTRAINT qc_lines_sum    CHECK (qty_accepted + qty_hold + qty_rejected = qty_delivered),
  CONSTRAINT qc_lines_reason CHECK ((qty_hold = 0 AND qty_rejected = 0) OR reason_code IS NOT NULL)
);

CREATE TABLE qc_line_checks (
  qc_line_id  bigint NOT NULL REFERENCES qc_lines(id) ON DELETE CASCADE,
  point_id    bigint NOT NULL REFERENCES qc_checklist_points(id),
  result      checklist_result NOT NULL,
  note        text,
  PRIMARY KEY (qc_line_id, point_id)
);

CREATE TABLE qc_hold_decisions (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  qc_line_id   bigint NOT NULL UNIQUE REFERENCES qc_lines(id),
  decision     hold_decision NOT NULL,
  qty          numeric(14,3) NOT NULL CHECK (qty > 0),
  reason       text   NOT NULL,
  decided_by   bigint NOT NULL REFERENCES app_users(id),
  decided_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE grns (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  grn_no           text   NOT NULL UNIQUE,
  po_id            bigint NOT NULL REFERENCES purchase_orders(id),
  gate_inward_id   bigint UNIQUE REFERENCES gate_inwards(id),   -- NULL only for legacy v1.0 GRNs
  qc_id            bigint UNIQUE REFERENCES qc_inspections(id),
  site_id          bigint NOT NULL REFERENCES sites(id),
  vendor_invoice_id bigint,                                    -- FK added after vendor_invoices
  status           grn_status NOT NULL DEFAULT 'GRN_DRAFT',
  is_legacy_v1     boolean NOT NULL DEFAULT false,
  flag_reason      text,
  rejection_reason text,
  approved_by      bigint REFERENCES app_users(id),
  approved_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT grn_v2_needs_qc   CHECK (is_legacy_v1 OR (gate_inward_id IS NOT NULL AND qc_id IS NOT NULL)),
  CONSTRAINT grn_flag_reason   CHECK (status <> 'GRN_FLAGGED' OR flag_reason IS NOT NULL),
  CONSTRAINT grn_reject_reason CHECK (status <> 'GRN_REJECTED' OR rejection_reason IS NOT NULL)
);
CREATE INDEX grns_po_status_idx ON grns (po_id, status);

CREATE TABLE grn_lines (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  grn_id           bigint NOT NULL REFERENCES grns(id) ON DELETE CASCADE,
  po_line_id       bigint NOT NULL REFERENCES po_lines(id),
  qc_line_id       bigint REFERENCES qc_lines(id),
  qty_accepted     numeric(14,3) NOT NULL CHECK (qty_accepted >= 0),   -- includes concession qty
  qty_concession   numeric(14,3) NOT NULL DEFAULT 0 CHECK (qty_concession >= 0),
  unit_rate        numeric(14,2) NOT NULL,
  location_id      bigint REFERENCES storage_locations(id),
  stock_entry_id   bigint REFERENCES stock_ledger(id),                 -- set on approval
  UNIQUE (grn_id, po_line_id),
  CONSTRAINT grn_lines_concession CHECK (qty_concession <= qty_accepted)
);
ALTER TABLE asset_units ADD CONSTRAINT asset_units_grn_line_fk FOREIGN KEY (source_grn_line_id) REFERENCES grn_lines(id);

-- Segregation of duty: receiver ≠ inspector ≠ approver (US-310)
CREATE OR REPLACE FUNCTION check_grn_segregation() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_receiver bigint; v_inspector bigint;
BEGIN
  IF NEW.approved_by IS NULL OR NEW.is_legacy_v1 THEN RETURN NEW; END IF;
  SELECT received_by INTO v_receiver FROM gate_inwards WHERE id = NEW.gate_inward_id;
  SELECT inspector_id INTO v_inspector FROM qc_inspections WHERE id = NEW.qc_id;
  IF NEW.approved_by IN (v_receiver, v_inspector) THEN
    RAISE EXCEPTION 'GRN approver must differ from the receiver and the inspector';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER grns_segregation BEFORE INSERT OR UPDATE OF approved_by ON grns
  FOR EACH ROW EXECUTE FUNCTION check_grn_segregation();

CREATE OR REPLACE FUNCTION check_qc_segregation() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_receiver bigint;
BEGIN
  SELECT received_by INTO v_receiver FROM gate_inwards WHERE id = NEW.gate_inward_id;
  IF NEW.inspector_id = v_receiver THEN
    RAISE EXCEPTION 'Inspector cannot be the user who logged the gate inward';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER qc_inspections_segregation BEFORE INSERT OR UPDATE OF inspector_id ON qc_inspections
  FOR EACH ROW EXECUTE FUNCTION check_qc_segregation();

-- Only APPROVED GRNs count toward PO received quantity (v1.0 rule)
CREATE VIEW v_po_line_receipt AS
SELECT pl.id AS po_line_id, pl.po_id, pl.item_id, pl.qty_ordered,
       coalesce(sum(gl.qty_accepted) FILTER (WHERE g.status IN ('GRN_APPROVED', 'GRN_CLOSED')), 0) AS qty_received,
       pl.qty_ordered
         - coalesce(sum(gl.qty_accepted) FILTER (WHERE g.status IN ('GRN_APPROVED', 'GRN_CLOSED')), 0) AS qty_outstanding
  FROM po_lines pl
  LEFT JOIN grn_lines gl ON gl.po_line_id = pl.id
  LEFT JOIN grns g       ON g.id = gl.grn_id
 GROUP BY pl.id;

CREATE TABLE shortfall_cases (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sht_no              text   NOT NULL UNIQUE,
  gate_inward_line_id bigint NOT NULL UNIQUE REFERENCES gate_inward_lines(id),
  po_line_id          bigint NOT NULL REFERENCES po_lines(id),
  qty_short           numeric(14,3) NOT NULL CHECK (qty_short > 0),
  decision            shortfall_decision NOT NULL DEFAULT 'PENDING',
  decided_by          bigint REFERENCES app_users(id),
  decided_at          timestamptz,
  closed_at           timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- 8. WAREHOUSE DAMAGE  (Module 4)
-- =============================================================================
CREATE TABLE damage_reports (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  dmg_no             text   NOT NULL UNIQUE,
  site_id            bigint NOT NULL REFERENCES sites(id),
  item_id            bigint NOT NULL REFERENCES items(id),
  asset_unit_id      bigint REFERENCES asset_units(id),
  location_id        bigint REFERENCES storage_locations(id),
  qty                numeric(14,3) NOT NULL CHECK (qty > 0),
  cause              damage_cause NOT NULL,
  observed_on        date   NOT NULL CHECK (observed_on <= current_date),
  source_grn_line_id bigint REFERENCES grn_lines(id),      -- drives warranty and valuation
  warranty_until     date,
  in_warranty        boolean GENERATED ALWAYS AS (warranty_until IS NOT NULL AND warranty_until >= observed_on) STORED,
  estimated_value    numeric(14,2) NOT NULL,
  status             damage_status NOT NULL DEFAULT 'DMG_REPORTED',
  decision           damage_decision,
  insurance_claim_ref text,
  quarantine_entry_id bigint REFERENCES stock_ledger(id),
  reported_by        bigint NOT NULL REFERENCES app_users(id),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dmg_warranty_claim CHECK (decision IS DISTINCT FROM 'WARRANTY_CLAIM' OR in_warranty),
  CONSTRAINT dmg_insurance_ref  CHECK (decision IS DISTINCT FROM 'WRITE_OFF' OR estimated_value <= 50000 OR insurance_claim_ref IS NOT NULL)
);

CREATE TABLE damage_inspections (
  damage_id     bigint NOT NULL REFERENCES damage_reports(id) ON DELETE CASCADE,
  inspector_id  bigint NOT NULL REFERENCES app_users(id),
  inspector_role role_code NOT NULL,                        -- CG_SMGR and CG_QC
  notes         text   NOT NULL,
  inspected_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (damage_id, inspector_id)
);

-- =============================================================================
-- 9. PURCHASE RETURN (RTV)  (Module 5)
-- =============================================================================
CREATE TABLE purchase_returns (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rtv_no            text   NOT NULL UNIQUE,
  site_id           bigint NOT NULL REFERENCES sites(id),
  vendor_id         bigint NOT NULL REFERENCES vendors(id),
  po_id             bigint NOT NULL REFERENCES purchase_orders(id),
  source            rtv_source NOT NULL,
  qc_id             bigint REFERENCES qc_inspections(id),
  damage_id         bigint REFERENCES damage_reports(id),
  shortfall_id      bigint REFERENCES shortfall_cases(id),
  basis             rtv_basis NOT NULL,
  vendor_rma_no     text,
  status            rtv_status NOT NULL DEFAULT 'RTV_DRAFT',
  prn_no            text UNIQUE,                            -- generated on approval
  gate_pass_no      text UNIQUE,                            -- RGP-…
  transporter       text,
  lr_no             text,
  eway_bill_no      text,
  raised_by         bigint NOT NULL REFERENCES app_users(id),
  approved_by       bigint REFERENCES app_users(id),
  approved_at       timestamptz,
  dispatched_at     timestamptz,
  acknowledged_at   timestamptz,
  closed_at         timestamptz,
  cancelled_reason  text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rtv_one_source CHECK (
    (source = 'QC_REJECTION'     AND qc_id IS NOT NULL AND damage_id IS NULL AND shortfall_id IS NULL) OR
    (source = 'WAREHOUSE_DAMAGE' AND damage_id IS NOT NULL AND qc_id IS NULL AND shortfall_id IS NULL) OR
    (source = 'SHORTFALL'        AND shortfall_id IS NOT NULL AND qc_id IS NULL AND damage_id IS NULL)),
  CONSTRAINT rtv_self_approval CHECK (approved_by IS NULL OR approved_by <> raised_by),
  CONSTRAINT rtv_approved_docs CHECK (status IN ('RTV_DRAFT', 'RTV_CANCELLED') OR (prn_no IS NOT NULL AND gate_pass_no IS NOT NULL))
);
ALTER TABLE gate_inwards ADD CONSTRAINT gate_inwards_rtv_fk FOREIGN KEY (replacement_rtv_id) REFERENCES purchase_returns(id);

CREATE TABLE purchase_return_lines (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rtv_id              bigint NOT NULL REFERENCES purchase_returns(id) ON DELETE CASCADE,
  po_line_id          bigint NOT NULL REFERENCES po_lines(id),
  item_id             bigint NOT NULL REFERENCES items(id),
  qty                 numeric(14,3) NOT NULL CHECK (qty > 0),
  unit_rate           numeric(14,2) NOT NULL,
  gst_rate            numeric(5,2)  NOT NULL,
  reason_code         text   NOT NULL,
  -- QC rejections never entered stock, so there is nothing to reverse
  reversal_entry_id   bigint REFERENCES stock_ledger(id),
  original_entry_id   bigint REFERENCES stock_ledger(id)      -- GRN posting being reversed
);

-- =============================================================================
-- 10. ACCOUNTS — invoices, debit notes, credit notes, reconciliation  (Module 6)
-- =============================================================================
CREATE TABLE vendor_invoices (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vendor_id      bigint NOT NULL REFERENCES vendors(id),
  po_id          bigint NOT NULL REFERENCES purchase_orders(id),
  invoice_no     text   NOT NULL,
  invoice_date   date   NOT NULL,
  place_of_supply char(2) NOT NULL,
  taxable_value  numeric(14,2) NOT NULL,
  cgst           numeric(14,2) NOT NULL DEFAULT 0,
  sgst           numeric(14,2) NOT NULL DEFAULT 0,
  igst           numeric(14,2) NOT NULL DEFAULT 0,
  total          numeric(14,2) GENERATED ALWAYS AS (taxable_value + cgst + sgst + igst) STORED,
  held_amount    numeric(14,2) NOT NULL DEFAULT 0,             -- returned / short quantity
  bill_control_ref text,
  status         invoice_status NOT NULL DEFAULT 'INV_RECEIVED',
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vi_tax_mode CHECK ((igst = 0) OR (cgst = 0 AND sgst = 0))
);
-- Duplicate invoice number per vendor blocked (v1.0 rule)
CREATE UNIQUE INDEX vendor_invoices_no_uq ON vendor_invoices (vendor_id, upper(btrim(invoice_no)));
ALTER TABLE grns ADD CONSTRAINT grns_invoice_fk FOREIGN KEY (vendor_invoice_id) REFERENCES vendor_invoices(id);

CREATE TABLE debit_notes (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  dn_no            text   NOT NULL UNIQUE,
  rtv_id           bigint UNIQUE REFERENCES purchase_returns(id),   -- exactly one per dispatch
  shortfall_id     bigint UNIQUE REFERENCES shortfall_cases(id),    -- short-close of billed qty
  vendor_id        bigint NOT NULL REFERENCES vendors(id),
  po_id            bigint NOT NULL REFERENCES purchase_orders(id),
  grn_id           bigint REFERENCES grns(id),
  vendor_invoice_id bigint REFERENCES vendor_invoices(id),          -- GST mirrors this
  taxable_value    numeric(14,2) NOT NULL CHECK (taxable_value > 0),
  cgst             numeric(14,2) NOT NULL DEFAULT 0,
  sgst             numeric(14,2) NOT NULL DEFAULT 0,
  igst             numeric(14,2) NOT NULL DEFAULT 0,
  total            numeric(14,2) GENERATED ALWAYS AS (taxable_value + cgst + sgst + igst) STORED,
  value_override_remark text,                                       -- Accounts may change value, never qty
  status           dn_status NOT NULL DEFAULT 'DEBIT_NOTE_PENDING',
  tally_voucher_ref text UNIQUE,
  issued_by        bigint REFERENCES app_users(id),
  issued_at        timestamptz,
  reconciled_at    timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dn_one_source CHECK ((rtv_id IS NOT NULL) <> (shortfall_id IS NOT NULL)),
  CONSTRAINT dn_tax_mode   CHECK ((igst = 0) OR (cgst = 0 AND sgst = 0)),
  CONSTRAINT dn_reconciled_needs_tally CHECK (status <> 'DN_RECONCILED' OR tally_voucher_ref IS NOT NULL)
);
CREATE INDEX debit_notes_open_idx ON debit_notes (vendor_id, status) WHERE status NOT IN ('DN_RECONCILED', 'DN_CANCELLED');

CREATE TABLE vendor_credit_notes (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vendor_id       bigint NOT NULL REFERENCES vendors(id),
  debit_note_id   bigint NOT NULL REFERENCES debit_notes(id),
  cn_no           text   NOT NULL,
  cn_date         date   NOT NULL,
  value           numeric(14,2) NOT NULL CHECK (value > 0),
  variance_pct    numeric(6,2),                                     -- set by trigger
  variance_flagged boolean NOT NULL DEFAULT false,                  -- > 2% blocks closure
  accepted_short_by bigint REFERENCES app_users(id),                -- Head of Finance override
  recorded_by     bigint NOT NULL REFERENCES app_users(id),
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX vendor_credit_notes_uq ON vendor_credit_notes (vendor_id, upper(btrim(cn_no)));

CREATE OR REPLACE FUNCTION compute_cn_variance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_dn numeric;
BEGIN
  SELECT total INTO v_dn FROM debit_notes WHERE id = NEW.debit_note_id;
  NEW.variance_pct     := round(abs(v_dn - NEW.value) / v_dn * 100, 2);
  NEW.variance_flagged := NEW.variance_pct > 2;
  RETURN NEW;
END $$;
CREATE TRIGGER vendor_credit_notes_variance BEFORE INSERT OR UPDATE OF value ON vendor_credit_notes
  FOR EACH ROW EXECUTE FUNCTION compute_cn_variance();

CREATE TABLE debit_note_offsets (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  debit_note_id      bigint NOT NULL REFERENCES debit_notes(id),
  vendor_invoice_id  bigint NOT NULL REFERENCES vendor_invoices(id),
  amount             numeric(14,2) NOT NULL CHECK (amount > 0),
  bill_control_ref   text,
  offset_by          bigint NOT NULL REFERENCES app_users(id),
  offset_at          timestamptz NOT NULL DEFAULT now()
);

-- Vendor ledger, both sides. Portal rows are written by the app; Tally rows are imported.
CREATE TABLE vendor_ledger_entries (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vendor_id      bigint NOT NULL REFERENCES vendors(id),
  side           ledger_side NOT NULL,
  entry_date     date   NOT NULL,
  doc_type       text   NOT NULL,          -- OPENING, INVOICE, PAYMENT, ADVANCE, DEBIT_NOTE, CREDIT_NOTE
  doc_ref        text   NOT NULL,
  amount         numeric(14,2) NOT NULL,   -- + raises payable (Cr), − reduces it (Dr)
  po_id          bigint REFERENCES purchase_orders(id),
  source_table   text,                     -- vendor_invoices / debit_notes / …
  source_id      bigint,
  tally_voucher_ref text,
  imported_at    timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX vendor_ledger_entries_idx ON vendor_ledger_entries (vendor_id, side, entry_date);

CREATE TABLE vendor_recon_runs (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vendor_id        bigint NOT NULL REFERENCES vendors(id),
  period_start     date   NOT NULL,
  period_end       date   NOT NULL,
  portal_balance   numeric(14,2) NOT NULL,
  tally_balance    numeric(14,2) NOT NULL,
  difference       numeric(14,2) GENERATED ALWAYS AS (portal_balance - tally_balance) STORED,
  held_amount      numeric(14,2) NOT NULL DEFAULT 0,
  status           recon_status NOT NULL DEFAULT 'RECON_OPEN',
  vendor_confirmed_balance numeric(14,2),
  reconciled_by    bigint REFERENCES app_users(id),
  reconciled_at    timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (vendor_id, period_start, period_end),
  CONSTRAINT recon_zero_to_close CHECK (status NOT IN ('RECON_RECONCILED', 'RECON_CONFIRMED_BY_VENDOR') OR portal_balance = tally_balance)
);

CREATE TABLE vendor_recon_items (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  run_id            bigint NOT NULL REFERENCES vendor_recon_runs(id) ON DELETE CASCADE,
  portal_entry_id   bigint REFERENCES vendor_ledger_entries(id),
  tally_entry_id    bigint REFERENCES vendor_ledger_entries(id),
  match_status      recon_match NOT NULL,
  note              text,
  resolved_by       bigint REFERENCES app_users(id),
  resolved_at       timestamptz,
  CONSTRAINT recon_item_has_side CHECK (portal_entry_id IS NOT NULL OR tally_entry_id IS NOT NULL OR match_status = 'OPEN_ITEM')
);

-- =============================================================================
-- 11. PLATFORM — documents, notifications, audit, transitions
-- =============================================================================
CREATE TABLE documents (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type     text   NOT NULL,          -- PR, QUOTATION, PO, GATE_INWARD, QC_LINE, GRN, DAMAGE, RTV, DEBIT_NOTE, VENDOR
  entity_id       bigint NOT NULL,
  doc_type        text   NOT NULL,          -- CHALLAN, INVOICE, PHOTO, DATA_LOGGER, PRN, GATE_PASS, KYC_PAN, …
  file_name       text   NOT NULL,          -- PO_Dhulagarh_0019.pdf
  storage_path    text   NOT NULL,
  mime_type       text   NOT NULL,
  size_bytes      bigint NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 10485760),
  sha256          char(64) NOT NULL,
  retention_class text   NOT NULL DEFAULT 'STATUTORY_8Y',
  virus_scanned   boolean NOT NULL DEFAULT false,
  uploaded_by     bigint NOT NULL REFERENCES app_users(id),
  uploaded_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX documents_entity_idx ON documents (entity_type, entity_id);

CREATE TABLE email_config (
  event_key     text PRIMARY KEY,           -- PR_APPROVED, RTV_DISPATCHED, DEBIT_NOTE_PENDING, …
  fixed_to      text[] NOT NULL DEFAULT '{}',
  cc            text[] NOT NULL DEFAULT '{}',
  bcc           text[] NOT NULL DEFAULT '{}',
  is_enabled    boolean NOT NULL DEFAULT true,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Outbox: a failed send never blocks the transaction
CREATE TABLE notification_outbox (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_key    text   NOT NULL REFERENCES email_config(event_key),
  entity_type  text   NOT NULL,
  entity_id    bigint NOT NULL,
  payload      jsonb  NOT NULL,
  status       text   NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'SENT', 'FAILED', 'DEAD')),
  attempts     smallint NOT NULL DEFAULT 0,
  last_error   text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  sent_at      timestamptz
);
CREATE INDEX notification_outbox_queue_idx ON notification_outbox (status, created_at) WHERE status IN ('QUEUED', 'FAILED');

-- Declared transitions; the API rejects anything not listed here
CREATE TABLE status_transitions (
  entity_type     text NOT NULL,
  from_status     text NOT NULL,
  to_status       text NOT NULL,
  permission_key  text NOT NULL,
  PRIMARY KEY (entity_type, from_status, to_status)
);

CREATE TABLE audit_log (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type  text   NOT NULL,
  entity_id    bigint NOT NULL,
  action       text   NOT NULL,             -- TRANSITION, UPDATE, OVERRIDE, PERMISSION_CHANGE, REJECTED_ATTEMPT
  from_status  text,
  to_status    text,
  before_data  jsonb,
  after_data   jsonb,
  user_id      bigint REFERENCES app_users(id),
  ip_address   inet,
  remarks      text,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_entity_idx ON audit_log (entity_type, entity_id, created_at);
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

-- Site code immutable once transactions exist (US-001 check DC-001)
CREATE OR REPLACE FUNCTION site_code_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code <> OLD.code AND EXISTS (SELECT 1 FROM material_requests WHERE site_id = OLD.id
                                      UNION ALL SELECT 1 FROM purchase_orders WHERE site_id = OLD.id LIMIT 1) THEN
    RAISE EXCEPTION 'Site code % cannot change once transactions exist', OLD.code;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER sites_code_immutable BEFORE UPDATE OF code ON sites
  FOR EACH ROW EXECUTE FUNCTION site_code_immutable();

-- updated_at maintenance
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['sites', 'items', 'vendors', 'asset_units', 'material_requests', 'stock_transfers',
                           'purchase_requests', 'purchase_orders', 'gate_inwards', 'grns', 'damage_reports',
                           'purchase_returns', 'debit_notes']
  LOOP
    EXECUTE format('CREATE TRIGGER %I_touch BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION touch_updated_at()', t, t);
  END LOOP;
END $$;

-- =============================================================================
-- 12. REPORTING VIEWS used by the dashboards
-- =============================================================================

-- Screen 1: stock by bucket with reorder status
CREATE VIEW v_stock_position AS
SELECT s.id AS site_id, s.name AS site, i.id AS item_id, i.code, i.name, i.uom,
       coalesce(sum(b.qty) FILTER (WHERE b.bucket = 'AVAILABLE'), 0)    AS available,
       coalesce(sum(b.qty) FILTER (WHERE b.bucket = 'RESERVED'), 0)     AS reserved,
       coalesce(sum(b.qty) FILTER (WHERE b.bucket = 'IN_TRANSIT'), 0)   AS in_transit,
       coalesce(sum(b.qty) FILTER (WHERE b.bucket = 'DAMAGED_HOLD'), 0) AS damaged_hold,
       coalesce(sum(b.qty) FILTER (WHERE b.bucket <> 'WRITTEN_OFF'), 0) AS on_hand,
       coalesce(iss.reorder_level, 0)                                   AS reorder_level,
       CASE WHEN coalesce(sum(b.qty) FILTER (WHERE b.bucket = 'AVAILABLE'), 0) < coalesce(iss.reorder_level, 0) THEN 'BELOW_REORDER'
            WHEN coalesce(sum(b.qty) FILTER (WHERE b.bucket = 'AVAILABLE'), 0) < coalesce(iss.reorder_level, 0) * 1.25 THEN 'NEAR_REORDER'
            ELSE 'HEALTHY' END AS stock_status
  FROM sites s
  CROSS JOIN items i
  LEFT JOIN stock_balances b       ON b.site_id = s.id AND b.item_id = i.id
  LEFT JOIN item_site_settings iss ON iss.site_id = s.id AND iss.item_id = i.id
 GROUP BY s.id, s.name, i.id, i.code, i.name, i.uom, iss.reorder_level;

-- Screen 2: group-wide surplus above each holding site's reorder level
CREATE VIEW v_group_surplus AS
SELECT site_id, site, item_id, code, greatest(available - reorder_level, 0) AS surplus
  FROM v_stock_position
 WHERE available > reorder_level;

-- Screen 6 scorecard: vendor quality from GRN / QC / RTV
CREATE VIEW v_vendor_scorecard AS
SELECT v.id AS vendor_id, v.legal_name,
       coalesce(sum(ql.qty_delivered), 0)                                AS qty_delivered,
       coalesce(sum(ql.qty_rejected), 0)                                 AS qty_rejected,
       round(100.0 * coalesce(sum(ql.qty_rejected), 0) / nullif(sum(ql.qty_delivered), 0), 2) AS rejection_pct,
       (SELECT count(*) FROM purchase_returns r WHERE r.vendor_id = v.id AND r.created_at > now() - interval '12 months') AS returns_12m
  FROM vendors v
  LEFT JOIN purchase_orders po  ON po.vendor_id = v.id
  LEFT JOIN gate_inwards gi     ON gi.po_id = po.id AND gi.arrived_at > now() - interval '12 months'
  LEFT JOIN qc_inspections qi   ON qi.gate_inward_id = gi.id
  LEFT JOIN qc_lines ql         ON ql.qc_id = qi.id
 GROUP BY v.id, v.legal_name;

-- =============================================================================
-- 13. AMENDMENTS  (Crystal Procurement 2.0 — see docs/00-decisions.md D-02)
--
-- Everything above this line is the supplied schema, byte-for-byte. The two
-- changes below were approved because the schema as supplied makes two
-- behaviours required by the brief impossible to build. Nothing is dropped or
-- redesigned; both changes are additive or in-place replacements.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- C-01  Transfer receipt needs two ledger legs against one transfer line.
--
-- The original idempotency key was source_type:source_id:movement. A transfer
-- receipt must post BOTH the source drain (IN_TRANSIT -> NULL at the sending
-- site) AND the destination credit (NULL -> AVAILABLE at the receiving site),
-- both keyed to the same stock_transfer_lines row with movement TRANSFER_IN.
-- Under the original key those two calls collided: the second returned the
-- first row's id and never posted, stranding the quantity in IN_TRANSIT at the
-- source and permanently overstating group stock.
--
-- Adding p_site_id makes the key unique per leg while keeping every single-site
-- movement exactly as idempotent as before (its key simply gains a stable
-- suffix). Function body only — no table, column or enum is touched.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION post_stock_movement(
  p_site_id bigint, p_item_id bigint, p_movement movement_type,
  p_from stock_bucket, p_to stock_bucket, p_qty numeric,
  p_source_type text, p_source_id bigint, p_user bigint,
  p_unit_value numeric DEFAULT NULL, p_location bigint DEFAULT NULL,
  p_asset_unit bigint DEFAULT NULL, p_reverses bigint DEFAULT NULL, p_remarks text DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
  v_key   text := p_source_type || ':' || p_source_id || ':' || p_movement || ':' || p_site_id;
  v_id    bigint;
  v_site  text;
BEGIN
  SELECT id INTO v_id FROM stock_ledger WHERE idempotency_key = v_key;
  IF FOUND THEN RETURN v_id; END IF;                    -- replay: already posted

  SELECT code INTO v_site FROM sites WHERE id = p_site_id;

  INSERT INTO stock_ledger (entry_no, site_id, item_id, location_id, asset_unit_id, movement, from_bucket, to_bucket,
                            qty, unit_value, source_type, source_id, reverses_entry_id, idempotency_key, posted_by, remarks)
  VALUES (next_document_no('SL', v_site), p_site_id, p_item_id, p_location, p_asset_unit, p_movement, p_from, p_to,
          p_qty, p_unit_value, p_source_type, p_source_id, p_reverses, v_key, p_user, p_remarks)
  RETURNING id INTO v_id;

  IF p_from IS NOT NULL THEN
    UPDATE stock_balances SET qty = qty - p_qty, last_entry_id = v_id
     WHERE site_id = p_site_id AND item_id = p_item_id AND bucket = p_from;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'No % stock for item % at site %', p_from, p_item_id, p_site_id;
    END IF;                                             -- CHECK (qty >= 0) blocks overdraw
  END IF;

  IF p_to IS NOT NULL THEN
    INSERT INTO stock_balances (site_id, item_id, bucket, qty, last_entry_id)
    VALUES (p_site_id, p_item_id, p_to, p_qty, v_id)
    ON CONFLICT (site_id, item_id, bucket)
    DO UPDATE SET qty = stock_balances.qty + EXCLUDED.qty, last_entry_id = EXCLUDED.last_entry_id;
  END IF;

  RETURN v_id;
END $$;

-- -----------------------------------------------------------------------------
-- C-02  QC re-inspection (SOP section 13) was unreachable.
--
-- qc_inspections.is_reinspection_of references the same table, but the column
-- also carried UNIQUE (gate_inward_id) — so a second inspection of the same
-- gate inward, which is exactly what a re-inspection is, could never be
-- inserted. The column was dead code.
--
-- A partial unique index keeps the real rule (one ORIGINAL inspection per gate
-- inward) while allowing a re-inspection chain. grns.qc_id UNIQUE still
-- guarantees one GRN per inspection, so the GRN links to whichever inspection
-- is final.
-- -----------------------------------------------------------------------------
ALTER TABLE qc_inspections DROP CONSTRAINT qc_inspections_gate_inward_id_key;

CREATE UNIQUE INDEX qc_inspections_gi_original
  ON qc_inspections (gate_inward_id) WHERE is_reinspection_of IS NULL;

CREATE INDEX qc_inspections_reinspection_idx
  ON qc_inspections (is_reinspection_of) WHERE is_reinspection_of IS NOT NULL;

COMMIT;
